<?xml version="1.0" encoding="utf-8"?><Database Name="CallQualityAssurance" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=server05;Initial Catalog=CallQualityAssurance;Integrated Security=True" SettingsObjectName="ClassLibrary1.Properties.Settings" SettingsPropertyName="CallQualityAssuranceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.QAUser" Member="QAUsers">
    <Type Name="QAUser">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Lastname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EnableFlag" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="QAUser_QAUserManage" Member="QAUserManages" ThisKey="UserID" OtherKey="UserID" Type="QAUserManage" />
    </Type>
  </Table>
  <Table Name="dbo.QAUserManage" Member="QAUserManages">
    <Type Name="QAUserManage">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SystemID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EnableFlag" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Association Name="QAUser_QAUserManage" Member="QAUser" ThisKey="UserID" OtherKey="UserID" Type="QAUser" IsForeignKey="true" />
    </Type>
  </Table>
</Database>